/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SplitMain } from "./SplitMain";
export type { SplitWallet } from "./SplitWallet";

export { SplitMain__factory } from "./factories/SplitMain__factory";
export { SplitWallet__factory } from "./factories/SplitWallet__factory";
