/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface SplitWalletInterface extends ethers.utils.Interface {
  functions: {
    "sendERC20ToMain(address,uint256)": FunctionFragment;
    "sendETHToMain(uint256)": FunctionFragment;
    "splitMain()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "sendERC20ToMain",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sendETHToMain",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "splitMain", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "sendERC20ToMain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendETHToMain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "splitMain", data: BytesLike): Result;

  events: {
    "ReceiveETH(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ReceiveETH"): EventFragment;
}

export class SplitWallet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SplitWalletInterface;

  functions: {
    sendERC20ToMain(
      token: string,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sendETHToMain(
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    splitMain(overrides?: CallOverrides): Promise<[string]>;
  };

  sendERC20ToMain(
    token: string,
    amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sendETHToMain(
    amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  splitMain(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    sendERC20ToMain(
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    sendETHToMain(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    splitMain(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    ReceiveETH(
      split?: string | null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { split: string; amount: BigNumber }
    >;
  };

  estimateGas: {
    sendERC20ToMain(
      token: string,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sendETHToMain(
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    splitMain(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    sendERC20ToMain(
      token: string,
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sendETHToMain(
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    splitMain(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
